PORT = "465"
EMAIL = "noreply@dnyx.in"
PASS_KEY="nury lttt cmrx vaga"

[connections.gsheets]

spreadsheet = "https://docs.google.com/spreadsheets/d/1Rnmp2Cu9Ud8q6x_YnA-_dvMLtBXF5CoqPjDuoeQecBE/"
worksheet = "<worksheet-gid-or-folder-id>"
type = "service_account" 
project_id = "leetcode-data-form"
private_key_id = "af7001a2b4b0fcbdc661287d3dcb4b763c489f51"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgWGNINSGDFne/\nNqJ8kNTMbyudxcsXAqVFcjJcQ99f4vslz98DTT6/HqwSrzljDtF1ASFxQ4+KcX92\nmJIMKCX1inc0KrwqNLMU+MqQbuORSBebdor43xle0Q99KyzvlYL1IxzGvP/DH1od\n6T4MACk9Pn2HKB06T0JRa5Jzy+HLZYxLitm1I1AO1xqAOfpPCWiP8Jz7MIgIVdEM\nOmoHAsySCeembvG4NTzp7B7o60G5FO8uV4qw6ML58PDdFJh1HecXeTpfAUtMx/XQ\nkUKUc/Mb/6Jwn/wGGU6MMqgeS/ClhNKrOaO1kWMlIerq9U7rTaCPAijgsVdr00Gf\n/i7W8LQ5AgMBAAECggEANHqpR+VHyhks6RLPHHjkhOJvwowNe8L8Z53IGMWIEuB9\ntXLy+SgrfK7jv5vE6wRbDnHnyaPEk5mxD5ZA2qS7Q8FlYVgJTMEByb/hwGLirVaM\nj2+9bVXLfmprKNrcMq/a9DNhRDRweyLEQlzn11KoLKjKudUpt79gI7jS7n5QsNpP\nNHz0S/Tn3Pb2is4d4iOU1jdCORBh+1JiHsjQf3UgUd0hevvwbGBpYHrzB7esmTjB\nUnUK4aRMZpNtJnufNjQvWezi4ZEZFXhTRlE7rdJh3kHtDLbBn3BQbAZ5E/IZ0oJ+\nB53/h78Ttbhb6hmJoMb/2sIbeL1+qUgYESsSMK9WTwKBgQDXDmzds5ARPpyq7USp\nMeaA2EEdemvntZ/wTf2LFw/Dj1s5nU/kMvmvH5OQrk1EMHLSqp5JQWkRnAfOxeex\n5/noOyil5LadJJI1K/UAQnc1JaJmBF1xX0Qmpi6vdx7YqdvEIaMe0HfdRqOUwAh5\nS2J0DokdXkXVljnDiA/HCRW7vwKBgQC+32nYjF1wQv3OT5tri/uxZdJ5biFa0rWG\nyXUceJFkPeeKQlIfsxzfNNUIGfFPlQqbm6GPgZcSsT+7HEGnO3JarOHX4x+FgW/r\nu4+yj/obrKTj4aAK3Hgl4iZa1l1zflCtdO8g++mFVZ86VfIJERjJsd3HmFhPla23\n3iPq9HPuBwKBgQCIiNgFSWNGD4JX4puc79lwI9vzYy3uxhjs8Bbwn4ualQFN6to1\n/0cWL+34BTF5AWlk5n3n9GdIjs9GL8+R272F+0krSbHGwtkweN/rckdMrsAUFOFe\ngSU7hHZPYEltNSoZs2FkxuXSzm48mk7G811mYXQb+SZNHDtAMLoTm2j48QKBgHds\nuAA6ytfLwpvMaVUgD8oOCGPbyVjXT6bW88Rtl6KdrPpvxox4+A6cMtJP0RFXEn0M\nIkj07z5N0q9S3a0x37nmQ6RdQkK5GvrmruEtfnLEUaMXb5h8G1ywpAjf6TazCO2O\npXQAyjqXuPm5/qc3oEfKVxZkNpUM9NV/Uv/WFZcPAoGBALtQ5+GbvS6Ypjkmtkru\n2QoKPa3Y5azB9XFV7hLNnIUdk8j1Q14bHvhLP6b2OjFZ33Wxo78ZHUFhLJS9qi0h\nXuvKharw50B6bHd54pSn/082bKPe7wzWkPDGQCZH8XX83E8Ffwcd1Bq0M7Jr+m9j\nx2PbpZy7X8O9iYCdc1o43JNN\n-----END PRIVATE KEY-----\n"

client_email = "leetcodedataform-python-access@leetcode-data-form.iam.gserviceaccount.com"

client_id = "103903203996690920849"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"

auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"

client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/leetcodedataform-python-access%40leetcode-data-form.iam.gserviceaccount.com"

